# Generated by Django 4.2.16 on 2024-10-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_management', '0003_project_is_syncing_project_last_sync_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokenLinkAnalysisStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_analyzing', models.BooleanField(default=False)),
                ('last_analysis', models.DateTimeField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('total_links', models.IntegerField(default=0)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broken_link_analysis_status', to='project_management.project')),
            ],
        ),
        migrations.CreateModel(
            name='BrokenLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('broken_url', models.URLField()),
                ('status_code', models.CharField(max_length=20)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broken_links', to='project_management.project')),
            ],
        ),
    ]
