# Generated by Django 4.2.16 on 2024-10-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbaglanti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlinkanalysisstatus',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
