# Generated by Django 4.2.16 on 2024-10-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbaglanti', '0002_brokenlinkanalysisstatus_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlink',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
