# Generated by Django 4.2.16 on 2024-10-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbaglanti', '0003_brokenlink_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlink',
            name='is_no_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokenlinkanalysisstatus',
            name='broken_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='brokenlinkanalysisstatus',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brokenlinkanalysisstatus',
            name='no_response_links',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='brokenlinkanalysisstatus',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
