# Generated by Django 4.2.16 on 2024-10-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disbaglanti', '0005_analysisresult_brokenlink_analysis_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokenlinkanalysisstatus',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
