# Generated by Django 4.2.16 on 2024-10-17 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disbaglanti', '0007_remove_brokenlink_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokenlink',
            name='project',
        ),
    ]
